### ISSUE TITLE
Dependencies and default implementations

### ISSUE THREAD

**Issue by joneshf** [purescript/purescript-control#1]
Moving `zipWithA` into `Control.Applicative` from `Control.Monad` is a good idea, but it causes an issue.

Since we can't do default implementations in typeclasses yet we have `<*` and `*>` in `Control.Applicative` rather than being in the typeclass and forcing everyone to implement these as well. A similar thing happens in `Data.Foldable` and `Data.Traversable` also since we could give a default implementation of each of the other functions in terms of just one.

Now, this causes an issue. `Control.Applicative` defines `zipWithA` which requires `sequence` which is imported from `Data.Traversable` which imports `Data.Foldable` for its constraints which imports `Control.Applicative` for constraints on some functions: `traverse_`, `for_`, and `sequence_.`.

So, we can either shuffle the definitions around, e.g. put `zipWithA` in `Data.Traversable` or something. We can move `<*` and `*>` into the typeclass and force everyone to implement these as well (the implementations that are there are fine, just would have to copy paste it everywhere :-1: ). Or we can try to get default implementations working.

Thoughts or other ideas?

**Comment by garyb** [comment]
Closing this as I guess we must have figured it out at some point in the last year :wink:
