### ISSUE TITLE
Merge Lazy, Lazy1, Lazy2

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-control#15]
I think this was just dumbness on my part. I don't know why these can't be one class.

**Comment by garyb** [comment]
Isn't `Lazy1` required for `Alternative`'s `some` and `maybe`?

**Comment by paf31** [comment]
Yes, but we could just use `Lazy (f a)`.

**Comment by garyb** [comment]
Hahah, right, yes! Oops.
