### ISSUE TITLE
Typeclass relationship diagram

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-control#16]
It would be really nice to have a diagram, like the one in the Prelude, of all the typeclasses in this package.

**Comment by garyb** [comment]
I'd been meaning to do one of these for a while, thanks for the reminder!

72451a3e755aa451ca9ad3bfc8228db529ef8bc5

**Comment by hdgarrood** [comment]
Hooray, thanks :)

**Comment by paf31** [comment]
:+1:
