### ISSUE TITLE
Draw a MonadZero out of MonadPlus?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-control#24]
See also: https://github.com/garyb/purescript-quickcheck-laws/issues/7

I think that the situation is this:
* Suppose we have some type `A :: * -> *` with `Alternative` and `Monad` instances.
* For such a type to have a `MonadPlus` instance, it currently needs to satisfy:
  * Distributivity: `(x <|> y) >>= f == (x >>= f) <|> (y >>= f)`
  * Annihilation: `empty >>= f = empty`
* There is at least one such type `A` for which `guard` is useful but which does not satisfy distributivity; `Maybe`.
* We want all our instances to be law-abiding, but we also want to be able to use functions like `guard` with types like `Maybe`.
* `guard` should include a constraint to ensure that the type satisifies annihilation.

Therefore, I propose that we add a new empty class as follows:

```purescript
class (Monad m, Alternative m) <= MonadZero m
```

with the annihilation law. Then, `MonadPlus` would only have a `MonadZero` constraint, and the distributivity law. Finally, `guard` should have a `MonadZero` constraint.

Then `Maybe` could have `MonadZero` but not `MonadPlus`, and we could use `guard` with it.

**Comment by paf31** [comment]
:+1: and `MonadOr` could be another subclass?

**Comment by garyb** [comment]
Works for me (+ `MonadOr`) :+1: 

This is what I spent endless hours trying to figure out the first time around, but I don't think I fully understood that it's the relationship between `Monad` and `Alternative` that these class should deal with, as I think I had `mzero`, `morelse`, `mplus` as suggested in the Haskell reform proposal... although we do lose the ability to have both `MonadOr` and `MonadPlus` instances here, but I guess for the few cases that can satisfy that a `newtype` could be used to direct the selection.

**Comment by paf31** [comment]
Why do we lose the ability to have both? I figured both would be subclasses of `MonadZero`.

**Comment by garyb** [comment]
I was talking about _types_ that could in theory have both `MonadPlus` and `MonadOr` instances, and also assuming we'd be relying on the `Alt` instance for either case - so we can't have an instance that satisfies both sets of laws, as the `Alt` instance has to be defined one way or the other. Or does the `MonadOr` operator break `Alt`'s laws anyway?

**Comment by paf31** [comment]
Isn't the `Alt` instance the same, just different laws?

**Comment by paf31** [comment]
I guess the question, as always, has to be: what can one do with a `MonadPlus` or a `MonadOr` that you can't do with a `MonadZero`? `guard` was the only use case I really had for `MonadPlus`.

**Comment by garyb** [comment]
I'm not sure, maybe we're talking about different things? I was assuming `MonadZero`, `MonadPlus` and `MonadOr` are all empty classes, but have different laws about how `(<|>)` and `(>>=)` interact. So we can't have a `Maybe` instance for `MonadPlus` and `MonadOr` at the same time and have everything satisfied.

**Comment by garyb** [comment]
Good point also, motivating cases would be useful.

**Comment by paf31** [comment]
I don't know if there is _any_ `MonadPlus` instance for `Maybe`, is there? `List` should have both, with the current instance, I think.

**Comment by safareli** [comment]
maybe could have instances of both, *MonadPlus reform proposal#[Instances of both](https://wiki.haskell.org/MonadPlus_reform_proposal#Instances_of_both)*
```hs
instance MonadPlus Maybe where
   mplus (Just a) Nothing = Just a
   mplus Nothing (Just a) = Just a
   mplus _ _ = Nothing
 
instance MonadOr Maybe where
   morelse (Just a) _ = Just a
   morelse _ b = b
```
