### ISSUE TITLE
Add (<$$>)

### ISSUE THREAD

**Issue by zudov** [purescript/purescript-control#26]
How about adding

```haskell
(<$$>) = (<$>) <<< (<$>)
```
to `Data.Functor` ?

I find myself often doing `map f <$> ...`, a shortcut for that might be nice.

**Comment by paf31** [comment]
I write `map <<< map` quite a lot, or the version you wrote, but I never felt it needed its own combinator in standard libraries. I think it might just make code harder to read honestly.

**Comment by zudov** [comment]
Fair enough
