### ISSUE TITLE
$> breaks operator symmetry

### ISSUE THREAD

**Issue by AppShipIt** [purescript/purescript-control#29]
```purs
g    $    x -- function over value
g   <$>   f -- function over Functor
g x <$    f --    value over Functor
-- flipped
  x  #  g   --    value over function
  f <#> g   --  Functor over function
  f  $> g x --  Functor over value
```
I feel strongly `$>` should be `#>`. Am I missing something?

**Comment by AppShipIt** [comment]
@garyb @hdgarrood Agreed? I'm not familiar with the deprecation process or I'd PR.

**Comment by garyb** [comment]
I don't know... `($>)` is the functor counterpart to `(*>)`, and works totally naturally in that regard.

**Comment by AppShipIt** [comment]
I get that. The difference being that `<*>` accepts the same type on both sides whereas anytime `$`/`<$>` is `flip`ped it becomes `#`/`<#>`. The documentation (and code correspondingly) reads: <q>a version of `(<$)` with its arguments flipped.</q> I don't believe changing the symbol to `#>` breaks symmetry with `*>`. But it does break what I see as beautiful intuition between operators and types. I stumbled on it [outlining basic operators](https://gist.github.com/AppShipIt/9350acf07a5f59520dde) for an Egghead lesson.

**Comment by garyb** [comment]
Ah I see. I don't feel particularly strongly about it because there's also a bit of a problem in that there's a mixing of two metaphors with these operators - angled brackets and `$` vs `#` are both signifying "direction". I guess ideally there should be `(<$)`, `($>)`, `(<#)`, `(#>)`, but that wouldn't really help the matter as one of the one-sided `$` and `#` varieties are always going to violate the intiution you're appealing to here.

**Comment by garyb** [comment]
The angled bracket direction thing coming from `(<<<)` and `(>>>)`, if that wasn't clear.

**Comment by hdgarrood** [comment]
I agree that the current choices of $, # <$>, <#> and how they relate makes sense, but you haven't persuaded me that the same idea should extend to <$ and $> in the way you suggest.

I do think changing it in this way would break a correspondence between <$, $>, <*, and *> unless we also were going to add a flipped version of <*> and rename *> in the same way (but I'm not really keen on that).

**Comment by AppShipIt** [comment]
I see your point (maybe) too. `<*>` doesn't have a `flip (<*>)` corollary (unlike `<$>`/`<#>`). Therefore although `(*>) = flip (<*)` it semantically conveys choice. So although `#>` looks more consistent in my outline (because of types) it could undermine the notion of choice with `<$>`. Am I close? I prefer `#>` for pedagogical reasons. My goals when I teach operators will be instilling intuition so that `<$>` (like `$` on a thing in a `<`box`>`) connects cognitively more than `map` (kinda like a loop). The choice operators and `>>=` (with Kleisli composition `>=>`) all imply passing the result of a function (or `Functor` of functions for `<*>`) on one side. This intuition is what breaks with `<$>` because it never accepted a function on that side (`<#>` did). See where I'm coming from?

**Comment by garyb** [comment]
As an aside I almost wish we'd never introduced `#` and `<#>`, since I only ever write code in `$` style I find it hard to flip my thinking when I encounter the opposite, and don't get me started on code that mixes the two...

**Comment by garyb** [comment]
My point about angle brackets denoting direction is that Kleisli compose and bind also have `=<<` and `<=<` variants though, which flip the function arrows just as `<$` does:

``` purescript
(>=>) :: (a -> m b) -> (b -> m c) -> a -> m c
(<=<) ::            ^ flip this 

($>) :: f a -> b -> f b
(<$) ::     ^ flip this 
```

**Comment by AppShipIt** [comment]
I personally love `#` and use it predominantly for its use case. It's more intuitive when pipelining data (like F#//LiveScript/Elm's `|>` or OOP's `.`). I agree they shouldn't be used in conjunction however. My `Cons` [example](https://gist.github.com/AppShipIt/d94ccab2e99d4d052897#file-main-purs-L14-L17) from purescript/purescript-foldable-traversable#44 illustrates the use case as well as @taylorfausak's [SVO stuff](https://twitter.com/taylorfausak/status/682341800237907968) in Neon.

**Comment by garyb** [comment]
Yeah, I understand the use case, it's the same argument for `(>>>)`. I was just commenting on a problem I have with it personally. 

The reason I prefer `(<<<)` and `$` is they preserve the normal ordering of function application:

``` purescript
f $ g $ h x = f (g (h x))
f <<< g <<< h $ x = f (g (h x))
```

Even if it does mean you have to read things "backwards" in a pipeline situation. I'd argue the only reason we think it's "backwards" is we happen to come from a culture that writes left-to-right.

**Comment by garyb** [comment]
As a compromise, what if we did add `<#` and `#>`? There is some redundancy there, but you could argue that about any of our flipped operations.

**Comment by AppShipIt** [comment]
I deleted two responses as I realized more deeply what you're saying. For documentation purposes: although `<*>` receives a `Functor` on both sides it's much closer in shape to `<$>` because one side is just functions lifted into the respective `Functor`. Therefore `<*` and `*>` effectively choose between results as if the left side (of functions) were evaluated. `<$` and `$>` likewise choose as if the left side (a function) were evaluated. `#>` and `<#` would simply be aliases choosing the opposite side without a corollary in `Apply`. For that reason maybe it's better left well enough alone?

**Comment by AppShipIt** [comment]
But naively `<*` and `*>` just pick the left or right <q>result</q> independently of which side of `<*>` is evaluated. That's why I thought (now uncertain either way) it made sense for `#>` to be the `flip` of `<$`

**Comment by garyb** [comment]
That's why I said "I don't know" in my first reply :smile:, I didn't mean it in the sense of doubting your conclusion, I just don't know what the best approach is given all the above.

`<$` and `$>` are slightly strange operators in this scheme, as unlike `<*` and `*>` which in some sense evaluate both sides and discard a result, they are more like "evaluate one side and then inject a different result value". The reason it makes sense to use `$` in the operator is it's functor-related, but since we have two different symbols for functor operators we end up with this problem.

**Comment by AppShipIt** [comment]
Because `<$` and `$>` imply <q>sidedness</q> instead of <q>flippedness</q> would `(#>) = ($>)`? That seems worse. I think `$>` is more correct but would still prefer `$>` for teaching in that scheme. It might be worth doing in Preface instead though.

**Comment by AppShipIt** [comment]
@hdgarrood I concluded above. TLDR; I see your point about `<*>` but given that `#>` would mean precisely `#>` I prefer the latter for its type symmetry illustrated in my original description and accompanying gist.

**Comment by hdgarrood** [comment]
What I'd like to happen, in order of preference:

1. Everything stays the same (sorry),
2. We remove `$>` and replace it with `#>`,
3. We add `#>` which is the same as `$>`.

You've categorised these six operators into two groups of three, but I'm just not convinced that `$>` and `<$` fit into your first and second group respectively. As far as I can see there's no common property shared by every element of either group (that isn't also shared by one or more elements of the other).

**Comment by hdgarrood** [comment]
For the avoidance of doubt: I'm really not very keen on either of my options 2 or 3, I just wanted to make it clear that introducing two different operators that do the same thing is :-1: :-1: :-1: whereas changing `$>` to `#>` is just :-1:.

**Comment by hdgarrood** [comment]
For instance, I think it's at least as sensible that `$>` should correspond to `$`, as both put the "value" (the thing to which a function is going to be applied) on the right, and likewise `<$` to `#`.

**Comment by AppShipIt** [comment]
> 1. Everything stays the same (sorry),

Status quo isn't that bad. Worst case I'm amenable to doing it in Preface which is intended to be more beginner friendly. But after writing it out below I again prefer `#>` here.

> there's no common property shared by every element of either group

They are symmetrical progressions to satisfy type transformations (probably wrong word). Their structure is:

| ID | Expression | Left | Right |
|---|---|---|---|
| 1 | `pure g <*> pure x` | function, lifted | value, lifted |
| 2a | `g $ x` | function | value |
| 2b | `g <$> pure x` | function | value, lifted |
| 2c | `g x <$ pure x` | function, applied | value, lifted, discarded |
| 2d | `pure (g x) <* pure x` | function, applied, lifted | value, lifted, discarded |
| 3a | `x # g` | value | function |
| 3b | `pure x <#> g` | value, lifted | function |
| 3c | _proposed:_ `pure x #> g x`  | value, lifted, discarded | function, applied |
| 3d | `pure x *> pure (g x)` | value, lifted, discarded | function, applied, lifted |
[[Previous outline](https://gist.github.com/AppShipIt/9350acf07a5f59520dde)]

NB…

1. Anywhere I write <q>function, applied</q> is purely conceptual but nonetheless holds true for the relationship between `>=>` (monadic functions), `>>=` (applied on one side), and `>>` (in Haskell applied on both sides).
2. As each of us noted, the shape of `<*>` is most like `<$>` thus unlike `<#>`.
3. To me, the shape of `*>` is unlike `<*>`:

  ```purs
-- pseudo
(<*>) :: f (a -> b) -> f a -> f b
(<* ) :: f       b  -> f a -> f b
( *>) :: f  a       -> f b -> f b
  ```
  `*>`  looks shaped as if there were some operator `(<&>) = flip (<*>)` whose right `Functor` of functions were applied against some other `Functor` to obtain its resultant `f b`. If `<&>` existed I might likewise expect `*>` to be called `&>` (kinda thankful it doesn't). But a flipped `<$>` does exist hence my intuition about `#>`. That `#>` would be implemented identically to `$>` reinforces my notion that `$>` doesn't fit semantically (any more than `<#`).

Final snippet with naive implementations:
```purs
(<#>) = flip (<$>)
( #>) = flip (<$ )
( *>) = flip (<* )
-- but hypothetically in some twisted prelude
(<&>) = flip (<*>)
( &>) = flip (<* )
```

> (that isn't also shared by one or more elements of the other).

Gist with alternate grouping? If neither of you is convinced it's not that big a deal and we can close.

**Comment by hdgarrood** [comment]
I'm brewing a response but in the meantime I think it's worth noting that `*>` is not `flip <*`: https://gist.github.com/hdgarrood/41c8f423a64ab218d681

**Comment by hdgarrood** [comment]
(@paf31 should http://try.purescript.org/?gist=41c8f423a64ab218d681 work?)

**Comment by AppShipIt** [comment]
Right my mistake. It nonetheless holds true `*>` is like `<*` if `<*>` were flipped which `<$>` does have a flipped variant. To reemphasize my motivation these operators are degenerate forms of one another:

* Need to combine a function with a value? `$`
* Your value is wrapped in a `Functor`? `<$>`
* Your function is already evaluated? `<$`
* Your value is wrapped in a `Functor`? `<*`

The same progression applies flipped except `$>` breaks symmetry with `<#>` which is bad for pedagogy. They are exactly the flip of one another and in both other flips marked by changing the symbol.

**Comment by AppShipIt** [comment]
@hdgarrood Your file has to be called `Main.purs` but it's on my todo list to work on if I get to it.

**Comment by paf31** [comment]
@hdgarrood It works for me ...

I think everything is consistent as it is. I think of the `$` functions as being derivable in terms of the `*` functions and `pure`:

- `x <$ fa` = `pure x <* fa`
- `fa $> x` = `fa *> pure x`
- `f <$> x` = `pure f <*> x`

Another way is to think in terms of `const`, but that's a bit more confusing IMO.

Now, `x <#> f = (#) <$> x <*> pure f`, so it's less clear what `<#` and `#>` should mean. I think we should just omit them.

**Comment by hdgarrood** [comment]
Haha, sorry - @AppShipIt was correct, it was broken until I changed the filename to Main.purs (previously it was something else).

**Comment by AppShipIt** [comment]
@paf31's reasoning makes sense to me especially after @hdgarrood's gist.
