### ISSUE TITLE
Include a class for `hoist`?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-control#30]
There's an `MFunctor` class in `Control.Monad.Morph` which is something like what I had in mind:

``` haskell
class MFunctor t where
  hoist :: Monad m => (forall a. m a -> n a) -> t m b -> t n b
```

But that imposes a monad constraint. I was thinking more like:

``` purescript
class Functor1 t where
  hoist :: (f ~> g) -> t f ~> t g
```

With the usual laws:

```
hoist (f ∘ g) = hoist f ∘ hoist g
hoist id = id
```

We have quite a few types with `hoist` operations when you get into free, yoneda, coroutines, etc.

**Comment by jdegoes** [comment]
`hoise` is in fact `map` for a higher-order `Functor`, where the objects are transformers and the arrows are natural transformations. 😄

**Comment by paf31** [comment]
Yes, `MFunctor` should be a functor in the category of monads (takes monads to monads, monad morphisms to monad morphisms). So maybe this should be called `FFunctor` or `FunctorFunctor` 😛

**Comment by garyb** [comment]
Isn't the `1` enough? :wink: That's our usual approach for higher order classes.

**Comment by paf31** [comment]
I think `Functor1` could possibly mean a few different things. Either `forall a. Functor (f a)`, or something from plain type constructors to type constructors, etc. There is also [stuff like `ProfunctorFunctor`](http://hackage.haskell.org/package/profunctors-5.2/docs/Data-Profunctor-Monad.html) etc., so we'll eventually want names where we can differentiate these things.

**Comment by garyb** [comment]
Ah yeah, that makes sense. What about `FunctorF` rather than `FFunctor` then? Since I assume it'd be `ProfunctorF` in that scheme also?

`FunctorFunctor` just seems too silly, even though it's entirely accurate :laughing:

**Comment by paf31** [comment]
It's sort of a shame that we can't write these classes once. I think we'd need at least polykinds and constraint kinds to do that.

I'm fine with any name that addresses the concern above.

**Comment by garyb** [comment]
I know! I've made attempts and doing them the right way in Haskell without much luck either, so either I was taking the wrong approach, or you need some really fancy type magic to make it work.

**Comment by paf31** [comment]
I wrote some thoughts along these lines a while ago [here](http://blog.functorial.com/posts/2012-02-02-Polykinded-Folds.html) actually.

**Comment by paf31** [comment]
I think `purescript-mmorph` and `purescript-hoist` are the way to go here. Close?

**Comment by garyb** [comment]
👍
