### ISSUE TITLE
Use fundeps for an intermediate representation in `defer`

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-control#47]
One issue with this typeclass I frequently come up against is that it almost always requires extra layers of thunks. For example, the `Lazy`, `List`, and `Cofree` data types all require an extra thunk which is immediately forced inside another suspension. This makes me hesitate to use it for something like a general purpose lazy fold because it's always going to carry a lot more overhead than necessary. Maybe we could have the class indexed by an intermediate representation?

```purescript
class Lazy rep a | a -> rep where
  defer :: (Unit -> rep) -> a

instance lazyLazy :: Lazy a (Z.Lazy a) where
  defer = Z.defer

instance lazyCofree :: Lazy (Tuple a (Cofree f a)) (Cofree f a) where
  defer = deferCofree

instance lazyList :: Lazy (Step a) (List a) where
  defer = List <<< Z.defer
```

**Comment by garyb** [comment]
@paf31 any thoughts on this? It seems like a good idea to me.

**Comment by paf31** [comment]
I'm thinking ... sorry for the delay :)

**Comment by paf31** [comment]
My initial reaction is "is this something a sufficiently decent optimizer would solve?" and "should we profile this to see if it's a big problem?" because it seems to complicate the types quite a bit more.

But also, won't you usually end up needing `a ~ rep` in order to implement `fix`?

**Comment by natefaubion** [comment]
Implementing a lazy fold with the current `Lazy` class results in twice as much allocation of thunks and twice as many steps to reduce. I don't see how you'd optimize around this in a general way because any optimization depends on the internals of whatever implements the Lazy type class.

```purescript
fix :: forall rep a. Lazy rep a => (a -> rep) -> a
```

I think that would still work fine, wouldn't it?

**Comment by paf31** [comment]
That would work, but it's not obvious to me that it's as useful in a generic setting.

**Comment by paf31** [comment]
Are you using this class generically or just for folds over a fixed container type? Can it be a separate combinator?

**Comment by natefaubion** [comment]
I want to use it to write a lazy foldr. The only possible way to write this is with `class Lazy` or by making it monomorphic to `Lazy`, otherwise you don't actually get any interesting laziness, because the producer must call `defer`. `class Lazy` is preferable to me because in the monormorphic case, you'll have to allocate thunks on top of a data type that's _already_ lazy. But if we use the existing representation, then the (what I anticipate) _common_ case of calculating a `Lazy a` result will be less efficient. If I were to choose between either or, I would choose to eschew `class Lazy`. The associated type is just an attempt to have both.

**Comment by natefaubion** [comment]
I've run some benchmarks and I've found a couple of things:
* foldr with maximum laziness implemented with Data.Lazy directly winds up being roughly the same as using Control.Lazy performance-wise (`find` implemented via `foldrLazy`).
* both are extremely slow (10x slower than specialized `find`).

So I'm happy to close this PR 😛
