### ISSUE TITLE
 purescript-control#^3.0.0 vs purescript-control#^4.0.0

### ISSUE THREAD

**Issue by sajalcody** [purescript/purescript-control#52]
`Unable to find a suitable version for purescript-control, please choose one by typing one of the numbers below:
    1) purescript-control#^3.0.0 which resolved to 3.3.1 and is required by purescript-monoid#3.3.0
    2) purescript-control#^4.0.0 which resolved to 4.1.0 and is required by purescript-either#4.1.1, purescript-foldable-traversable#4.1.1, purescript-identity#4.1.0, purescript-lazy#4.0.0, purescript-lists#5.4.0, purescript-maybe#4.0.1, purescript-nonempty#5.0.0, purescript-tuples#5.1.0`

**Comment by hdgarrood** [comment]
GitHub issue trackers are not for these sorts of questions; please use Slack or Discourse instead.
