### ISSUE TITLE
class Lazy1 f where defer1 :: forall a. (Unit -> f a) -> f a

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-control#54]
Using Lazy is not that useful sometimes and having something like

`class Lazy1 f where defer1 :: forall a. (Unit -> f a) -> f a`

would be great

**Comment by JordanMartinez** [comment]
Will we be implementing this change?

**Comment by hdgarrood** [comment]
Since adding this would be a non-breaking change, I'd like to leave it until after the 0.14.0 dust settles, at least. There also doesn't appear to be much demand for it, which is an argument against including it in the core libraries.

**Comment by JordanMartinez** [comment]
Meaning, why can't this just be implemented outside of core as a separate lib?

Yeah, since this isn't breaking, then I'll ignore it for now.

**Comment by hdgarrood** [comment]
Yes, I think things should not be included in the core libraries unless we expect them to get a decent amount of use.

**Comment by JordanMartinez** [comment]
This should be implemented outside of the core libraries.
